<<<<<<< HEAD
import { AuthProvider } from '../providers/AuthProvider';
=======
// File: src/app/layout.tsx
import { AuthProvider } from '../contexts/AuthContext';
import { AuthInitializer } from '../components/AuthInitializer';
>>>>>>> 847dd36 (Updataed components)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
<<<<<<< HEAD
          {children}
=======
          <AuthInitializer>
            {children}
          </AuthInitializer>
>>>>>>> 847dd36 (Updataed components)
        </AuthProvider>
      </body>
    </html>
  );
}
